prerequisites: fix sudo not found error

diff --git a/tools/prerequisites b/tools/prerequisites
--- a/tools/prerequisites
+++ b/tools/prerequisites
@@ -96,6 +96,10 @@ detect_linux() {
 	echo "$NAME$VERSION"
 }
 
+detect_sudo() {
+	which sudo 2>/dev/null || { [ "$(id -u)" -eq 0 ] || { echo "Error: sudo not found" >&2; exit 1; } }
+}
+
 install_requisite() {
 	local OSV="$1" ARG="$2"DOY="$3"
 
@@ -112,9 +116,9 @@ install_requisite() {
 	echo -e "\nPackages for '$OSV':\n$vals\n"
 	[ "${ARG:0:1}" == "s" ] && exit 0
 	case "$OSV" in
-		Fedora*)                                      sudo dnf --refresh  install $DOY $vals || exit 1 ;;
-		Debian*|Devuan*|LMDE*) sudo apt-get update && sudo apt            install $DOY $vals || exit 1 ;;
-		Ubuntu*|Mint*)         sudo apt-get update && sudo apt-get        install $DOY $vals || exit 1 ;;
+		Fedora*)                                                $(detect_sudo) dnf --refresh  install $DOY $vals || exit 1 ;;
+		Debian*|Devuan*|LMDE*) $(detect_sudo) apt-get update && $(detect_sudo) apt            install $DOY $vals || exit 1 ;;
+		Ubuntu*|Mint*)         $(detect_sudo) apt-get update && $(detect_sudo) apt-get        install $DOY $vals || exit 1 ;;
 		*)                     echo 'No known installer'                                     && exit 1 ;;
 	esac
 	exit 0
